services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=capstone
      - POSTGRES_PASSWORD=capstone123
      - POSTGRES_DB=capstone
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    
volumes:
  postgres:
