name: capstone-ui-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: 
      - frontend/capstone-ui/**
      - .github/workflows/capstone-ui-test.yml

jobs:
  ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/capstone-ui
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: frontend/capstone-ui
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
